"""Initial migration

Revision ID: 86a235959da
Revises: None
Create Date: 2016-06-29 22:20:02.624000

"""

# revision identifiers, used by Alembic.
revision = '86a235959da'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
